sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "9"

script:
  - npm test

after_script:
  - npm run cover
  - npm run coveralls

matrix:
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "9"

notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"
